[package]
name = "accountverifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fantoccini = { version = "0.19.3", features = ["rustls-tls"]}
tokio = { version = "1.29.1", features = ["full"] }
